# file: bastion.yml
#
# Applies the bastion configuration.
#
---

- name: LOCAL INVENTORY
  hosts: localhost
  connection: local
  tasks:
  - add_host: name="{{ ansible_fqdn }}" groups=bastion

- name: FIREWALL
  hosts: bastion
  connection: local
  roles:
  - admin_access_sources
